=== liptga/kickassalternate/trunk/com.ind.commithook/xsd/config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" xmlns="http://code.google.com/p/kickassalternate" targetNamespace="http://code.google.com/p/kickassalternate">
	<xsd:element name="CommitHookConfig">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="Check" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="Check">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="Parameters" minOccurs="0">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element ref="Parameter" minOccurs="1" maxOccurs="unbounded"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="Include" minOccurs="0">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element ref="RegexpPattern" minOccurs="1" maxOccurs="unbounded"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="Exclude" minOccurs="0">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element ref="RegexpPattern" minOccurs="1" maxOccurs="unbounded"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
			<xsd:attribute name="className" type="xsd:string" use="required"/>
			<xsd:attribute name="legend" type="xsd:string" use="required"/>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="RegexpPattern">
		<xsd:complexType>
			<xsd:attribute name="value" type="xsd:string" use="required"/>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="Parameter">
		<xsd:complexType>
			<xsd:attribute name="name" type="xsd:string" use="required"/>
			<xsd:attribute name="value" type="xsd:string" use="required"/>
		</xsd:complexType>
	</xsd:element>	
</xsd:schema>

=== liptga/kickassalternate/trunk/com.ind.commithook/samples/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<hook:CommitHookConfig xmlns:hook="http://code.google.com/p/kickassalternate" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://code.google.com/p/kickassalternate ../xsd/config.xsd ">
  <TempDirectory>d:\eclipse\temp</TempDirectory>
  <hook:Check className="com.ind.commithook.checkers.CommentChecker">
    <Parameters>
      <hook:Parameter name="minLenght" value="30"/>
    </Parameters>
    <Include>
      <hook:RegexpPattern value=""/>
    </Include>
    <Exclude>
      <hook:RegexpPattern value=""/>
    </Exclude>
  </hook:Check>
  <hook:Check className="com.ind.commithook.checkers.CheckStyle">
    <Parameters>
      <hook:Parameter name="minLenght" value="30"/>
    </Parameters>
    <Include>
      <hook:RegexpPattern value=""/>
    </Include>
    <Exclude>
      <hook:RegexpPattern value=""/>
    </Exclude>
  </hook:Check>
</hook:CommitHookConfig>

=== liptga/kickassalternate/com.ind.commithook/samples/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<CommitHookConfig xmlns="http://code.google.com/p/kickassalternate" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://code.google.com/p/kickassalternate ../xsd/config.xsd ">
  <Check className="com.ind.commithook.checkers.CommentChecker" legend="Comments Checker">
    <Parameters>
      <Parameter name="minLength" value="20"/>
      <Parameter name="pattern" value="JIRABUGID-\d*:.*"/>
    </Parameters>
    <Include>
      <RegexpPattern value=".*\.java"/>
    </Include>
    <Exclude>
      <RegexpPattern value=".*/test/.*\.java"/>
    </Exclude>
  </Check>
  <Check className="com.ind.commithook.checkers.CheckStyle" legend="Java CheckStyle General Checker">
    <Parameters>
      <Parameter name="configFile" value="D:\Eclipse\commithook\com.ind.commithook\samples\checkstyle.xml"/>
    </Parameters>
  </Check>
</CommitHookConfig>
